name: UdaConnect - Package with Docker

on:
#  push:
#    branches: [main]
  workflow_dispatch:

jobs:
  build_custom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push locations-kafa
        uses: docker/build-push-action@v2
        with:
          context: ./modules/locations-kafka
          file: ./modules/locations-kafka/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aldolinux/udaconnect-locations-kafka:latest                
      - name: Build and push persons-grpc
        uses: docker/build-push-action@v2
        with:
          context: ./modules/persons-grpc
          file: ./modules/persons-grpc/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aldolinux/udaconnect-persons-grpc:latest
  build_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend
          file: ./modules/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aldolinux/udaconnect-app:latest
      - name: Build and push connections-api
        uses: docker/build-push-action@v2
        with:
          context: ./modules/connections-api
          file: ./modules/connections-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aldolinux/udaconnect-connections-api:latest
      - name: Build and push persons-api
        uses: docker/build-push-action@v2
        with:
          context: ./modules/persons-api
          file: ./modules/persons-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aldolinux/udaconnect-persons-api:latest
      - name: Build and push locations-api
        uses: docker/build-push-action@v2
        with:
          context: ./modules/locations-api
          file: ./modules/locations-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aldolinux/udaconnect-locations-api:latest   